# This is a basic workflow to help you get started with Actions

name: Daily

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - id: randomness
        name: 50% chance to do the commit
        run: echo "PROCEED=$((RANDOM%2))" >> $GITHUB_ENV
        shell: bash

      - name: Echo the proceed variable
        run: echo env.PROCEED
        shell: bash
        
      - if: env.PROCEED == '0'
        name: Cancelling
        uses: andymckay/cancel-action@0.2
      
      - if: env.PROCEED == '0'
        name: Waiting for cancellation
        run: sleep 30
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      
      - name: Set git info
        run: |
          git config --global user.email "bradyryun@gmail.com"
          git config --global user.name "Brady Ryun"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "${{ steps.date.outputs.date }}" > date.txt
          git add .
          git commit -m "${{ steps.date.outputs.date }}"
          git push -f origin main
