# This is a basic workflow to help you get started with Actions

name: Daily

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "${{ steps.date.outputs.date }}" > date.txt
          git add .
          git commit -m "Brand new commit"
          git push origin master
